# Generated by Django 4.1 on 2022-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
    ]
