# Generated by Django 4.1 on 2022-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0002_item"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="name",),
        migrations.AddField(
            model_name="item",
            name="checkers_price",
            field=models.FloatField(default=0.01, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="pnp_price",
            field=models.FloatField(default=0.01, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="title",
            field=models.CharField(default=0.01, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="woolworths_price",
            field=models.FloatField(default=0.01, max_length=10),
            preserve_default=False,
        ),
    ]
