# Generated by Django 4.1 on 2022-09-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0004_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="CompareItem",),
        migrations.DeleteModel(name="CompareProject",),
        migrations.DeleteModel(name="CompareWork",),
    ]
