from item_1_brown_bread_loaf import main_brown_bread
from item_2_two_litre_fresh_milk_full_cream import main_two_litre_milk_fresh_full_cream
from item_3_tuna_tin_brine import main_tuna_tin_brine
from item_4_toilet_paper_18 import main_toilet_paper_18
from item_5_sweet_chili_corn_chips import main_sweet_chili_corn_chips
from item_6_strawberries_punnet import main_strawberries_punnet
from item_7_baked_beans_tin import main_baked_beans_tin
from item_8_white_hamburger_rolls import main_white_hamburger_rolls
from item_9_lettuce_head import main_lettuce_head
from item_10_spaghetti_500g import main_spaghetti_500g
from item_11_button_mushrooms_250g import main_button_mushrooms_250g


main_brown_bread()
main_two_litre_milk_fresh_full_cream()
main_tuna_tin_brine()
main_toilet_paper_18()
main_sweet_chili_corn_chips()
main_strawberries_punnet()
main_baked_beans_tin()
main_white_hamburger_rolls()
main_lettuce_head()
main_spaghetti_500g()
main_button_mushrooms_250g()